version: '3.8'

services:
  chesterton-microservice:
    build: .
    container_name: chesterton-microservice-dev
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - WORDPRESS_SITE_URL=${WORDPRESS_SITE_URL}
      - DB_URL=${DB_URL}
      - XML_URL=${XML_URL}
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./scripts:/app/scripts:ro  # Montar scripts en modo solo lectura
      - ./faqs_markdown:/app/faqs_markdown
      - ./pages:/app/pages
      - ./posts:/app/posts
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - chesterton-network
    # Para desarrollo, ejecutar en modo interactivo
    stdin_open: true
    tty: true

networks:
  chesterton-network:
    driver: bridge 